version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: based_pg_password
      POSTGRES_DB: based_pg
    ports:
      - 54322:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  pgdata:
